name: opioid-research
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - beautifulsoup4
  - jupyter
  - matplotlib
  - nb_conda
  - nltk
  - pandas
  - plotly
  - psycopg2   # For PostgreSQL
  - pydocstyle
  - pylint
  - seaborn
  - spacy
  - sqlalchemy
  - textblob
  - tweepy

# Package to manually install
# - dataset
