name: opioid-research
dependencies:
  - python=3.6
  - jupyter
  - matplotlib
  - nb_conda
  - pandas
  - psycopg2   # For PostgreSQL
  - pydocstyle
  - pylint
  - seaborn
  - sqlalchemy
  - textblob
  - tweepy
