name: opioid-research
dependencies:
  - python=3.6
  - jupyter
  - matplotlib
  - nb_conda
  - pandas
  - plotly
  - psycopg2   # For PostgreSQL
  - pylint
  - seaborn
  - sqlalchemy

# Packages to manually install
# - dataset
# - pydocstyle
# - textblob
# - tweepy
